# Default values for name: k8s-dns-node-cache-chart
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: k8s-dns-node-cache
namespace: kube-system
serviceType: managed

userID: 33
groupID: 33

# This is the name of the Kubernete Service resource that exposes the traditional CoreDNS service within the cluster.
corednsServiceName: coredns

image:
  registry: quay.io
  name: k8s-dns-node-cache
  tag: 1.21.1

updateStrategy:
  rollingUpdate:
    maxUnavailable: 10%

ports:
  dns:
    name: dns
    targetPort: 53
    port: 53
  prometheus: 9253
  liveness: 8080

resources:
  limits:
    cpu: 50m
    memory: 15Mi
  requests:
    cpu: 25m
    memory: 5Mi

configmap:
  cache:
    success: 30
    denial: 5

test:
  image:
    name: giantswarm/alpine-testing
    tag: 0.1.1
