# Default values for name: k8s-dns-node-cache-chart
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: k8s-dns-node-cache
namespace: kube-system
serviceType: managed

image:
  registry: quay.io
  name: giantswarm/k8s-dns-node-cache
  tag: 1.21.4

updateStrategy:
  rollingUpdate:
    maxUnavailable: 10%

cluster:
  kubernetes:
    DNS:
      IP: 172.31.0.10
    clusterDomain: cluster.local

ports:
  prometheus: 9253
  liveness: 8080

# Reference of the traditional coredns pods.
upstreamService:
  # The port the traditional coredns service is listening to.
  servicePort: 53
  # The port the traditional coredns pods are listening to.
  podPort: 1053
  # The value of the `k8s-app` label for the traditional coredns pods.
  appName: coredns

resources:
  limits:
    cpu: 500m
    memory: 150Mi
  requests:
    cpu: 250m
    memory: 50Mi

configmap:
  cache:
    success: 30
    denial: 5

verticalPodAutoscaler:
  enabled: true

test:
  image:
    name: giantswarm/alpine-testing
    tag: 0.1.1
