apiVersion: cilium.io/v2
kind: CiliumLocalRedirectPolicy
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  redirectFrontend:
    serviceMatcher:
      serviceName: coredns
      namespace: {{ .Values.namespace }}
  redirectBackend:
    localEndpointSelector:
      matchLabels:
        {{- include "labels.selector" . | nindent 8 }}
    toPorts:
      - port: "{{ .Values.upstreamService.servicePort }}"
        name: dns
        protocol: UDP
      - port: "{{ .Values.upstreamService.servicePort }}"
        name: dns-tcp
        protocol: TCP

