apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
data:
  Corefile: |
    {{ .Values.cluster.kubernetes.clusterDomain }}:{{ .Values.upstreamService.servicePort }} {
        errors
        cache {
                success 9984 {{ .Values.configmap.cache.success }}
                denial 9984 {{ .Values.configmap.cache.denial }}
        }
        reload
        loop
        bind {{ .Values.nodeLocalListenAddress }} {{ .Values.cluster.kubernetes.DNS.IP }}
        forward . __PILLAR__CLUSTER__DNS__ {
                force_tcp
        }
        prometheus :{{ .Values.ports.prometheus }}
        health {{ .Values.nodeLocalListenAddress }}:{{ .Values.ports.liveness }}
    }
    in-addr.arpa:{{ .Values.upstreamService.servicePort }} {
        errors
        cache {{ .Values.configmap.cache.success }}
        reload
        loop
        bind {{ .Values.nodeLocalListenAddress }} {{ .Values.cluster.kubernetes.DNS.IP }}
        forward . __PILLAR__CLUSTER__DNS__ {
                force_tcp
        }
        prometheus :{{ .Values.ports.prometheus }}
    }
    ip6.arpa:{{ .Values.upstreamService.servicePort }} {
        errors
        cache {{ .Values.configmap.cache.success }}
        reload
        loop
        bind {{ .Values.nodeLocalListenAddress }} {{ .Values.cluster.kubernetes.DNS.IP }}
        forward . __PILLAR__CLUSTER__DNS__ {
                force_tcp
        }
        prometheus :{{ .Values.ports.prometheus }}
    }
    .:{{ .Values.upstreamService.servicePort }} {
        errors
        cache {{ .Values.configmap.cache.success }}
        reload
        loop
        bind {{ .Values.nodeLocalListenAddress }} {{ .Values.cluster.kubernetes.DNS.IP }}
        forward . __PILLAR__UPSTREAM__SERVERS__
        prometheus :{{ .Values.ports.prometheus }}
    }
