apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
data:
  Corefile: |
    {{ .Values.cluster.kubernetes.clusterDomain }}:{{ .Values.upstreamService.servicePort }} {
        errors
        template ANY AAAA {
                rcode NOERROR
        }
        cache {
                success 9984 {{ .Values.configmap.cache.success }}
                denial 9984 {{ .Values.configmap.cache.denial }}
        }
        reload
        loop
        bind 0.0.0.0
        forward . __PILLAR__CLUSTER__DNS__ {
                force_tcp
        }
        prometheus :{{ .Values.ports.prometheus.coredns }}
        health 0.0.0.0:{{ .Values.ports.liveness }}
    }
    in-addr.arpa:{{ .Values.upstreamService.servicePort }} {
        errors
        cache {{ .Values.configmap.cache.success }}
        reload
        loop
        bind 0.0.0.0
        forward . __PILLAR__CLUSTER__DNS__ {
                force_tcp
        }
        prometheus :{{ .Values.ports.prometheus.coredns }}
    }
    ip6.arpa:{{ .Values.upstreamService.servicePort }} {
        errors
        cache {{ .Values.configmap.cache.success }}
        reload
        loop
        bind 0.0.0.0
        forward . __PILLAR__CLUSTER__DNS__ {
                force_tcp
        }
        prometheus :{{ .Values.ports.prometheus.coredns }}
    }
    .:{{ .Values.upstreamService.servicePort }} {
        errors
        template ANY AAAA {
                rcode NOERROR
        }
        cache {{ .Values.configmap.cache.success }}
        reload
        loop
        bind 0.0.0.0
        forward . __PILLAR__CLUSTER__DNS__ {
                force_tcp
        }
        prometheus :{{ .Values.ports.prometheus.coredns }}
    }
