kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.name }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      k8s-app: {{ .Values.name }}
  ingress:
  - ports:
    - port: {{ .Values.upstreamService.servicePort }}
      protocol: UDP
    - port: {{ .Values.upstreamService.servicePort }}
      protocol: TCP
    - port: {{ .Values.ports.prometheus }}
      protocol: TCP
  egress:
  - {}
  policyTypes:
  - Egress
  - Ingress
