apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  privileged: false
  allowPrivilegeEscalation: false
  # Add back CAP_NET_BIND_SERVICE so that coredns can run on port 53
  allowedCapabilities:
  - NET_BIND_SERVICE
  volumes:
    - 'configMap'
    - 'hostPath'
    - 'projected'
  hostNetwork: true
  hostIPC: false
  hostPID: false
  hostPorts:
  - min: {{ .Values.ports.dns.targetPort }}
    max: {{ .Values.ports.dns.targetPort }}
  - min: {{ .Values.ports.prometheus }}
    max: {{ .Values.ports.prometheus }}
  runAsUser:
    rule: 'MustRunAsNonRoot'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  readOnlyRootFilesystem: true
