{{- if not .Values.global.podSecurityStandards.enforced }}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'unconfined'
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  allowedCapabilities: 
    - 'NET_ADMIN'
  volumes:
    - 'configMap'
    - 'hostPath'
    - 'projected'
  hostNetwork: true
  hostIPC: false
  hostPID: false
  hostPorts:
  - min: {{ .Values.upstreamService.servicePort }}
    max: {{ .Values.upstreamService.servicePort }}
  - min: {{ .Values.ports.prometheus.nodecache }}
    max: {{ .Values.ports.prometheus.nodecache }}
  - min: {{ .Values.ports.prometheus.coredns }}
    max: {{ .Values.ports.prometheus.coredns }}
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  readOnlyRootFilesystem: false
{{- end }}
