# A headless service is a service with a service IP but instead of load-balancing it will return the IPs of our associated Pods.
# We use this to expose metrics to Prometheus.
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
    giantswarm.io/monitoring: "true"
spec:
  selector:
    k8s-app: {{ .Values.name }}
  clusterIP: None
  ports:
  - name: metrics
    port: {{ .Values.ports.prometheus.nodecache }}
    targetPort: {{ .Values.ports.prometheus.nodecache }}
  - name: coredns
    port: {{ .Values.ports.prometheus.coredns }}
    targetPort: {{ .Values.ports.prometheus.coredns }}
