apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  selector:
    k8s-app: {{ .Values.name }}
  clusterIP: {{ .Values.cluster.kubernetes.DNS.IP }}
  ports:
  - name: {{ .Values.ports.dns.name }}
    port: {{ .Values.ports.dns.port }}
    targetPort: {{ .Values.ports.dns.targetPort }}
    protocol: UDP
  - name: {{ .Values.ports.dns.name }}-tcp
    port: {{ .Values.ports.dns.port }}
    targetPort: {{ .Values.ports.dns.targetPort }}
    protocol: TCP
