apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-upstream
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  ports:
  - name: dns
    port: 53
    protocol: UDP
    targetPort: {{ .Values.upstreamService.podPort }}
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: {{ .Values.upstreamService.podPort }}
  selector:
    k8s-app: {{ .Values.upstreamService.appName }}
