{{ if .Capabilities.APIVersions.Has "autoscaling.k8s.io/v1" }}
{{ if .Values.verticalPodAutoscaler.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: node-cache
      controlledValues: RequestsAndLimits
      maxAllowed:
        cpu: 100m
        memory: 50Mi
      minAllowed:
        cpu: 50m
        memory: 25Mi
  targetRef:
    apiVersion: apps/v1
    kind: DaemonSet
    name:  {{ .Values.name }}
  updatePolicy:
    updateMode: Auto
{{ end }}
{{ end }}
